/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.tekolang

import kotlin.test.Test
import kotlin.test.assertNotNull

class MainTest {
  @Test
  fun testAppHasAGreeting() {
    val classUnderTest = Main()
    assertNotNull(classUnderTest.toString(), "app should have a greeting")
  }
}
